[project]
name = "grafo-transferencias-futebol"
version = "0.1.0"
description = "Projeto de visualização de transfêrencias de times de futebol em grafos"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "httpx>=0.28.1",
]
